title: "Replication Package for CoLiCo"
description: "Replication Package for our paper:<br>Beyond Literal Meaning: Uncover and Explain Implicit Knowledge in Code through Wikipedia-based Concept Linking"
theme: jekyll-theme-cayman
