title: "Replication Package for FSE'21 submission #514"
description: "Beyond Literal Meaning: Uncover and Explain Implicit Knowledge in Code through Wikipedia-based Concept Linking"
theme: jekyll-theme-cayman
